# .coderabbit.yaml
language: de-DE
reviews:
  profile: "assertive"
  path_filters:
    - "src/**"
    - "docs/**"
    - "**/*.md"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/*.d.ts"
    - "!*.lock"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!pnpm-lock.yaml"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
