<?php

namespace App\Http\Controllers\Tablefy;

use App\Models\Customer;
use App\Tablefy\TablefyController;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Validation\Rule;

/**
 * @generated by `php artisan make:tablefy-resource Customer`
 *
 * Alles CRUD erbt von TablefyController. Hier stehen nur die resource-spezifischen
 * Angaben + die Validierungsregeln. Voll editierbar (z.B. Authorization, eager loading).
 */
class CustomerController extends TablefyController
{
    protected string $model = Customer::class;

    protected string $folder = 'Customers';
    protected string $singular = 'Customer';
    protected string $plural = 'Customers';
    protected string $routeName = 'customers';

    protected function rules(?Model $record = null): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'email', Rule::unique('customers', 'email')->ignore($record)],
            'status' => ['required', Rule::in(['active', 'inactive'])],
            'total_spent' => ['nullable', 'numeric', 'min:0'],
        ];
    }
}
