// @generated by `php artisan make:tablefy-resource Customer`
// Quelle: Migration/DB-Schema der Tabelle `customers`.
// NICHT von Hand bearbeiten – wird beim nächsten Generator-Lauf überschrieben.

export type Customer = {
  id: number;
  name: string;
  email: string;
  status: "active" | "inactive";
  total_spent: number;
  created_at: string;
  updated_at: string;
};
